In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

In [2]:
df_housing = pd.read_csv('housing_data.csv')
df_housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
2  392.83   4.03   34.7  
3  394.63   2.94   33.4  
4  396.90   5.33   36.2

In [3]:
df_housing.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'PRICE'],
      dtype='object')

In [4]:
# To scale numeric features, select numeric feaures
df_housing_numeric = df_housing[['CRIM', 'ZN', 'INDUS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']]

In [5]:
# Scale the numeric feaures and convert to DataFrame
X_scaler = StandardScaler()
num_scaled = X_scaler.fit_transform(df_housing_numeric)
df_num_scaled = pd.DataFrame(num_scaled, columns = df_housing_numeric.columns)
df_num_scaled.head()

CRIM        ZN     INDUS       NOX        RM       AGE       DIS  \
0 -0.419782  0.284830 -1.287909 -0.144217  0.413672 -0.120013  0.140214   
1 -0.417339 -0.487722 -0.593381 -0.740262  0.194274  0.367166  0.557160   
2 -0.417342 -0.487722 -0.593381 -0.740262  1.282714 -0.265812  0.557160   
3 -0.416750 -0.487722 -1.306878 -0.835284  1.016303 -0.809889  1.077737   
4 -0.412482 -0.487722 -1.306878 -0.835284  1.228577 -0.511180  1.077737   

        RAD       TAX   PTRATIO         B     LSTAT  
0 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  
1 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  
2 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  
3 -0.752922 -1.106115  0.113032  0.416163 -1.361517  
4 -0.752922 -1.106115  0.113032  0.441052 -1.026501

In [6]:
X = pd.concat([df_num_scaled, df_housing['CHAS']], axis = 1)
y = df_housing['PRICE']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

In [9]:
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_train = lr.predict(X_train)
y_pred_test = lr.predict(X_test)

train_r2 = r2_score(y_train, y_pred_train)
test_r2 = r2_score(y_test, y_pred_test)
print('Train R2 ', train_r2)
print('Test R2  ', test_r2)

Train R2  0.7645451026942549
Test R2   0.6733825506400195


## Regularization

### Ridge

In [16]:
# Build and evaluate Ridge model
ridge_model = Ridge(alpha=15)
ridge_model.fit(X_train, y_train)

y_pred_train = ridge_model.predict(X_train)
y_pred_test = ridge_model.predict(X_test)

train_r2 = r2_score(y_train, y_pred_train)
test_r2 = r2_score(y_test, y_pred_test)
print('Train R2 ', train_r2)
print('Test R2  ', test_r2)


Train R2  0.7615932777564829
Test R2   0.6633646941226767


In [17]:
lr.coef_

array([-1.04242529,  1.03604084,  0.0777311 , -1.8789804 ,  2.70876672,
       -0.28079317, -3.1560096 ,  2.10632153, -1.86413286, -2.20120069,
        0.62151065, -3.47239016,  2.51124642])

In [18]:
ridge_model.coef_

array([-0.94710626,  0.82124672, -0.15078425, -1.44977417,  2.81800252,
       -0.30650829, -2.6529765 ,  1.34303025, -1.20693677, -2.12771833,
        0.64648273, -3.2798639 ,  1.62293063])

In [26]:
# Build and evaluate Lasso model

lasso_model = Lasso(alpha=0.5)
lasso_model.fit(X_train, y_train)

y_pred_train = lasso_model.predict(X_train)
y_pred_test = lasso_model.predict(X_test)

train_r2 = r2_score(y_train, y_pred_train)
test_r2 = r2_score(y_test, y_pred_test)
print('Train R2 ', train_r2)
print('Test R2  ', test_r2)


Train R2  0.7160339248758933
Test R2   0.6118941818344068


In [27]:
lasso_model.coef_

array([-0.30082783,  0.        , -0.        , -0.        ,  2.97749168,
       -0.        , -0.14900164, -0.        , -0.23458223, -1.99082504,
        0.31402724, -3.43702718,  0.        ])

In [ ]:
# Build and evaluate ElasticNet  model
en_model = ElasticNet(alpha=1, l1_ratio = 0.5)
en_model.fit(X_train, y_train)

y_pred_train = en_model.predict(X_train)
y_pred_test = en_model.predict(X_test)

train_r2 = r2_score(y_train, y_pred_train)
test_r2 = r2_score(y_test, y_pred_test)
print('Train R2 ', train_r2)
print('Test R2  ', test_r2)

## Grid Search

In [28]:
from sklearn.model_selection import GridSearchCV

In [30]:
# Grid Search - Ridge
param = {'alpha':[0.01,0.1, 1, 10, 20, 30]}

model = Ridge()

grid_cv = GridSearchCV(estimator=model, param_grid= param, cv=5, 
                       scoring='r2')
grid_cv.fit(X_train, y_train)
grid_cv.best_params_


{'alpha': 20}

In [31]:
# Lasso
param = {'alpha':[ 0.001, 0.01,  0.1, 1]}

model = Lasso()

grid_cv = GridSearchCV(estimator=model, param_grid= param, cv=5, scoring='r2' )
grid_cv.fit(X_train, y_train)
grid_cv.best_params_


{'alpha': 0.01}

In [ ]:
# ElasticNet
param = {'alpha':[ 0.01, 0.1, 0.3, 0.5],
         'l1_ratio': [0.3, 0.5, 0.7, 0.9]}

algo_name = ElasticNet()

grid_cv = GridSearchCV(estimator=algo_name, param_grid= param, cv=5, scoring='r2' )
grid_cv.fit(X_train, y_train)
grid_cv.best_params_